image:
  name: "choisunguk/jmeter"
  tag: "latest"

master:
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: worker1
  persistence:
    enabled: true
    mountPath: "/jmeter/apache-jmeter-3.3/script.jmx"
    hostPath:
      path:  "/tmp/script.jmx"

server:
  replicaCount: 2