apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:  
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/jenkins
    server: 192.168.219.99
  claimRef:
    name: jenkins-pvc
    namespace: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi