  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    app: my-example-prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus"