alertmanager:
  ingress:
    enabled: false
    # change here
    hosts:
      - choilab.com
prometheus:
  # change here
  prometheusSpec:
    routePrefix: /prom
    # change here
    nodeSelector: 
      kubernetes.io/hostname: k8s-worker-1
    storageSpec:
      volumeClaimTemplate:
        spec:          
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
        selector:
          matchLabels:
            app: prometheus
  ingress:
    enabled: true
    # change here
    hosts:
      - choilab.com
    # change here
    paths:
      - /prom
grafana:
  adminPassword: password1234
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    # change here
    path: /grafana/?(.*)
    hosts:
      - choilab.com