prometheus:
  # change here
  prometheusSpec:
    routePrefix: /prom
    # change here
    nodeSelector: 
      kubernetes.io/hostname: k8s-worker-1
    storageSpec:
      volumeClaimTemplate:
        spec:          
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
        selector:
          matchLabels:
            app: my-example-prometheus
  ingress:
    enabled: true
    # change here
    hosts:
      - choilab.com
    # change here
    paths:
      - /prom
grafana:
  adminPassword: password1234
  ingress:
    enabled: true
    # change here
    path: /grafana
    hosts:
      - choilab.com
  grafana.ini:
    server:
      root_url: http://choilab.com/grafana
      domain: choilab.com