persistence:
  size: 20Gi
  existingClaim: jenkins-pvc

controller:
  image: "choisunguk/jenkins"
  tag: "v4"
  installPlugins: []
  nodeSelector: 
    kubernetes.io/hostname: k8s-worker-1
  jenkinsUriPrefix: "/jenkins"
  ingress:
    enabled: true
    hostName: "choilab.com"
    path: "/jenkins"