persistence:
  size: 20Gi
  existingClaim: jenkins-pvc
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  # mounts:
  # - name: docker-sock
  #   mountPath: /var/run/docker.sock

controller:
  image: "choisunguk/jenkins"
  tag: "v4"
  installPlugins: []
  nodeSelector: 
    kubernetes.io/hostname: k8s-worker-1
  jenkinsUriPrefix: "/jenkins"
  ingress:
    enabled: true
    hostName: "choilab.com"
    path: "/jenkins"
  customInitContainers:
  - name: custom-init
    image: "alpine:3.7"
    imagePullPolicy: Always
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    command: ["/bin/sh"]
    args: ["-c", "chmod 644 /var/run/docker.sock"]
