apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
spec:
  selector:
    app: nginx-test
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80