apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "distributed-jmeter.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    helm.sh/chart: {{ include "distributed-jmeter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
spec:
  replicas: {{ .Values.master.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  {{ include "distributed-jmeter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: master
    spec:
      {{- if .Values.matser.nodeSelector }}
      nodeSelector: {{ .Values.matser.nodeSelector }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"          
          args:
            - master
          ports:
            - containerPort: 60000
        {{- if .Values.master.persistence.enabled }}
        volumeMounts:
        - name: jmx
          mountPath: {{ .Values.master.persistence.mountPath }}
        {{- end }}
      {{- if .Values.master.persistence.enabled }}
      volumes:
        - name: jmx
          hostPath:
            path: {{ .Values.master.persistence.hostPath.path }}
      {{- end }}

